# BROADCOM diag for Northstar2
obj-y += memtest.o memory_diags.o
obj-y += qspi_diags.o
obj-y += i2c_diags.o
obj-y += uart_diags.o
obj-y += nand_diags.o
obj-y += mdio_diags.o
obj-y += mdio_wrappers.o
obj-y += usb20_diags.o
#obj-y += usb20_device_mode_diags.o
obj-y += usb30_diags.o
obj-y += aon_gpio_diags.o
obj-y += sata_diags.o
obj-y += pcie_diags.o
obj-y += audio_diags.o
obj-y += mmc_diags.o
obj-y += spi_diags.o
obj-y += tamper_diags.o
obj-y += gmac_diags.o
obj-y += spdif_diags.o

