#
# Copyright 2016 Broadcom Ltd.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= ns2_cmds.o
obj-$(CONFIG_BCM_NS2_CHIMP)	+= ns2_nvram_store.o ns2_nvram.o chimp.o
obj-$(CONFIG_SCSI_AHCI_PLAT)	+= ns2_sata.o
obj-$(CONFIG_BCM_NS2_PCIE)	+= ns2_pcie.o

