# BROADCOM diagnostics packages

obj-y += memtest.o MEMORY_diags.o
obj-y += UART_diags.o
obj-y += QSPI_diags.o
obj-y += SPI_diags.o
obj-y += MMC_diags.o
obj-y += NAND_diags.o
obj-y += MDIO_wrappers.o
obj-y += PCIE_diags.o
obj-y += PWM_diags.o
obj-y += SPDIF_diags.o
obj-y += AUDIO_diags.o
obj-y += AON_GPIO_diags.o
obj-y += I2C_diags.o
obj-y += USB_diags.o
obj-y += TAMPER_diags.o
obj-y += SATA_diags.o
obj-y += GMAC_diags.o
