/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy_cl45ven_rdb.h
    @brief RDB File for BRPHY_CL45VEN

    @version 2019Jan21_rdb
*/

#ifndef BRPHY_CL45VEN_RDB_H
#define BRPHY_CL45VEN_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY_CL45VEN_FORCE_LINK_TYPE;
#define BRPHY_CL45VEN_FORCE_LINK_FORCE_LINK_MODE_MASK (0x8000U)
#define BRPHY_CL45VEN_FORCE_LINK_FORCE_LINK_MODE_SHIFT (15U)
#define BRPHY_CL45VEN_FORCE_LINK_CHNG_10GBASET_AN_CTRL_BEHAV_MASK (0x4000U)
#define BRPHY_CL45VEN_FORCE_LINK_CHNG_10GBASET_AN_CTRL_BEHAV_SHIFT (14U)
#define BRPHY_CL45VEN_FORCE_LINK_CHNG_BIT13_MCTRL_RD_BEHAV_MASK (0x2000U)
#define BRPHY_CL45VEN_FORCE_LINK_CHNG_BIT13_MCTRL_RD_BEHAV_SHIFT (13U)
#define BRPHY_CL45VEN_FORCE_LINK_AN_FLP_BTB_TMR_MODE_MASK (0x1000U)
#define BRPHY_CL45VEN_FORCE_LINK_AN_FLP_BTB_TMR_MODE_SHIFT (12U)
#define BRPHY_CL45VEN_FORCE_LINK_SWP_UFORMATED_CODE_FLDS_MASK (0x800U)
#define BRPHY_CL45VEN_FORCE_LINK_SWP_UFORMATED_CODE_FLDS_SHIFT (11U)
#define BRPHY_CL45VEN_FORCE_LINK_BRK_LNK_TMR_MODE_MASK (0x400U)
#define BRPHY_CL45VEN_FORCE_LINK_BRK_LNK_TMR_MODE_SHIFT (10U)
#define BRPHY_CL45VEN_FORCE_LINK_PREAMBLE_IGNORE_MASK (0x200U)
#define BRPHY_CL45VEN_FORCE_LINK_PREAMBLE_IGNORE_SHIFT (9U)
#define BRPHY_CL45VEN_FORCE_LINK_FORCE_LNK_10GBASET_FDX_MASK (0x100U)
#define BRPHY_CL45VEN_FORCE_LINK_FORCE_LNK_10GBASET_FDX_SHIFT (8U)
#define BRPHY_CL45VEN_FORCE_LINK_FORCE_LNK_1000BASET_FDX_HDX_MASK (0x80U)
#define BRPHY_CL45VEN_FORCE_LINK_FORCE_LNK_1000BASET_FDX_HDX_SHIFT (7U)
#define BRPHY_CL45VEN_FORCE_LINK_IGNORE_ACK2_MASK (0x40U)
#define BRPHY_CL45VEN_FORCE_LINK_IGNORE_ACK2_SHIFT (6U)
#define BRPHY_CL45VEN_FORCE_LINK_LNK_FORCE_100BASET_OK_MASK (0x20U)
#define BRPHY_CL45VEN_FORCE_LINK_LNK_FORCE_100BASET_OK_SHIFT (5U)
#define BRPHY_CL45VEN_FORCE_LINK_LNK_FORCE_100BASET_RDY_MASK (0x10U)
#define BRPHY_CL45VEN_FORCE_LINK_LNK_FORCE_100BASET_RDY_SHIFT (4U)
#define BRPHY_CL45VEN_FORCE_LINK_DIS_REG7P0_BIT13_AUTO_UPDATE_MASK (0x8U)
#define BRPHY_CL45VEN_FORCE_LINK_DIS_REG7P0_BIT13_AUTO_UPDATE_SHIFT (3U)
#define BRPHY_CL45VEN_FORCE_LINK_LNK_FORCE_10BASET_OK_MASK (0x4U)
#define BRPHY_CL45VEN_FORCE_LINK_LNK_FORCE_10BASET_OK_SHIFT (2U)
#define BRPHY_CL45VEN_FORCE_LINK_LNK_FORCE_10BASET_RDY_MASK (0x2U)
#define BRPHY_CL45VEN_FORCE_LINK_LNK_FORCE_10BASET_RDY_SHIFT (1U)
#define BRPHY_CL45VEN_FORCE_LINK_LAST_PG_TO_EN_MASK (0x1U)
#define BRPHY_CL45VEN_FORCE_LINK_LAST_PG_TO_EN_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_SELECTIVE_RESET_TYPE;
#define BRPHY_CL45VEN_SELECTIVE_RESET_DSP_RESET_MASK (0x8000U)
#define BRPHY_CL45VEN_SELECTIVE_RESET_DSP_RESET_SHIFT (15U)
#define BRPHY_CL45VEN_SELECTIVE_RESET_SM_DSP_RESET_MASK (0x4000U)
#define BRPHY_CL45VEN_SELECTIVE_RESET_SM_DSP_RESET_SHIFT (14U)
#define BRPHY_CL45VEN_SELECTIVE_RESET_DIG100_RESET_MASK (0x80U)
#define BRPHY_CL45VEN_SELECTIVE_RESET_DIG100_RESET_SHIFT (7U)




typedef uint16_t BRPHY_CL45VEN_TEST_FSM_EXT_NXT_PGS_TYPE;
#define BRPHY_CL45VEN_TEST_FSM_EXT_NXT_PGS_XNP_XMTR_STATE_MASK (0x7000U)
#define BRPHY_CL45VEN_TEST_FSM_EXT_NXT_PGS_XNP_XMTR_STATE_SHIFT (12U)
#define BRPHY_CL45VEN_TEST_FSM_EXT_NXT_PGS_XNP_RCVR_STATE_MASK (0x700U)
#define BRPHY_CL45VEN_TEST_FSM_EXT_NXT_PGS_XNP_RCVR_STATE_SHIFT (8U)
#define BRPHY_CL45VEN_TEST_FSM_EXT_NXT_PGS_ARB_STATE_MASK (0xf0U)
#define BRPHY_CL45VEN_TEST_FSM_EXT_NXT_PGS_ARB_STATE_SHIFT (4U)
#define BRPHY_CL45VEN_TEST_FSM_EXT_NXT_PGS_HCD_STATE_MASK (0xfU)
#define BRPHY_CL45VEN_TEST_FSM_EXT_NXT_PGS_HCD_STATE_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_TEST_FSM_NXT_PGS_TYPE;
#define BRPHY_CL45VEN_TEST_FSM_NXT_PGS_NP_XMTR_STATE_MASK (0x3e0U)
#define BRPHY_CL45VEN_TEST_FSM_NXT_PGS_NP_XMTR_STATE_SHIFT (5U)
#define BRPHY_CL45VEN_TEST_FSM_NXT_PGS_NP_RCVR_STATE_MASK (0xfU)
#define BRPHY_CL45VEN_TEST_FSM_NXT_PGS_NP_RCVR_STATE_SHIFT (0U)




typedef uint8_t BRPHY_CL45VEN_RESERVED_TYPE;




typedef uint16_t BRPHY_CL45VEN_AN_MAN_TEST_TYPE;
#define BRPHY_CL45VEN_AN_MAN_TEST_LP_PG_TO_CAPTURE_MASK (0xf00U)
#define BRPHY_CL45VEN_AN_MAN_TEST_LP_PG_TO_CAPTURE_SHIFT (8U)
#define BRPHY_CL45VEN_AN_MAN_TEST_LNK_PARTNR_NXT_PG_TEST_MODE_MASK (0x4U)
#define BRPHY_CL45VEN_AN_MAN_TEST_LNK_PARTNR_NXT_PG_TEST_MODE_SHIFT (2U)
#define BRPHY_CL45VEN_AN_MAN_TEST_MAN_TEST_EN_SEED_MASK (0x2U)
#define BRPHY_CL45VEN_AN_MAN_TEST_MAN_TEST_EN_SEED_SHIFT (1U)
#define BRPHY_CL45VEN_AN_MAN_TEST_MAN_TEST_EN_MASK (0x1U)
#define BRPHY_CL45VEN_AN_MAN_TEST_MAN_TEST_EN_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_AMLPAA_TYPE;
#define BRPHY_CL45VEN_AMLPAA_MAN_LP_1000TX_HDX_MASK (0x8000U)
#define BRPHY_CL45VEN_AMLPAA_MAN_LP_1000TX_HDX_SHIFT (15U)
#define BRPHY_CL45VEN_AMLPAA_MAN_LP_1000TX_FDX_MASK (0x4000U)
#define BRPHY_CL45VEN_AMLPAA_MAN_LP_1000TX_FDX_SHIFT (14U)
#define BRPHY_CL45VEN_AMLPAA_MAN_LP_PORT_TYPE_MASK (0x2000U)
#define BRPHY_CL45VEN_AMLPAA_MAN_LP_PORT_TYPE_SHIFT (13U)
#define BRPHY_CL45VEN_AMLPAA_MAN_LP_MS_CONFIG_VALUE_MASK (0x1000U)
#define BRPHY_CL45VEN_AMLPAA_MAN_LP_MS_CONFIG_VALUE_SHIFT (12U)
#define BRPHY_CL45VEN_AMLPAA_MAN_LP_MS_MANUAL_CONFIG_EN_MASK (0x800U)
#define BRPHY_CL45VEN_AMLPAA_MAN_LP_MS_MANUAL_CONFIG_EN_SHIFT (11U)
#define BRPHY_CL45VEN_AMLPAA_MAN_LP_SEED_MASK (0x7ffU)
#define BRPHY_CL45VEN_AMLPAA_MAN_LP_SEED_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_AMLPAB_TYPE;
#define BRPHY_CL45VEN_AMLPAB_MAN_LP_PMA_TRAINING_RESET_REQ_MASK (0x10U)
#define BRPHY_CL45VEN_AMLPAB_MAN_LP_PMA_TRAINING_RESET_REQ_SHIFT (4U)
#define BRPHY_CL45VEN_AMLPAB_MAN_LP_PHY_SHORT_REACH_MODE_MASK (0x4U)
#define BRPHY_CL45VEN_AMLPAB_MAN_LP_PHY_SHORT_REACH_MODE_SHIFT (2U)
#define BRPHY_CL45VEN_AMLPAB_MAN_LP_LOOP_TIMING_ABILITY_MASK (0x2U)
#define BRPHY_CL45VEN_AMLPAB_MAN_LP_LOOP_TIMING_ABILITY_SHIFT (1U)
#define BRPHY_CL45VEN_AMLPAB_MAN_LP_10GBASET_CAPABILITY_MASK (0x1U)
#define BRPHY_CL45VEN_AMLPAB_MAN_LP_10GBASET_CAPABILITY_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_A_TYPE;
#define BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_A_LP_NP_A_MASK (0xffffU)
#define BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_A_LP_NP_A_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_B_TYPE;
#define BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_B_LP_NP_B_MASK (0xffffU)
#define BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_B_LP_NP_B_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_C_TYPE;
#define BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_C_LP_NP_C_MASK (0xffffU)
#define BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_C_LP_NP_C_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_D_TYPE;
#define BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_D_LP_NP_D_MASK (0xffffU)
#define BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_D_LP_NP_D_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_E_TYPE;
#define BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_E_LP_NP_E_MASK (0xffffU)
#define BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_E_LP_NP_E_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_F_TYPE;
#define BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_F_LP_NP_F_MASK (0xffffU)
#define BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_F_LP_NP_F_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_EPON_CTRL_REG_TYPE;
#define BRPHY_CL45VEN_EPON_CTRL_REG_EPON_MODE_MASK (0x200U)
#define BRPHY_CL45VEN_EPON_CTRL_REG_EPON_MODE_SHIFT (9U)
#define BRPHY_CL45VEN_EPON_CTRL_REG_EOC_PACKET_NORM_MASK (0x100U)
#define BRPHY_CL45VEN_EPON_CTRL_REG_EOC_PACKET_NORM_SHIFT (8U)
#define BRPHY_CL45VEN_EPON_CTRL_REG_EPON_MODE_CRCCHECK_MASK (0x80U)
#define BRPHY_CL45VEN_EPON_CTRL_REG_EPON_MODE_CRCCHECK_SHIFT (7U)
#define BRPHY_CL45VEN_EPON_CTRL_REG_TX_EN_EXTEND_MASK (0x40U)
#define BRPHY_CL45VEN_EPON_CTRL_REG_TX_EN_EXTEND_SHIFT (6U)
#define BRPHY_CL45VEN_EPON_CTRL_REG_EOC_MODE_POLARITY_MASK (0x20U)
#define BRPHY_CL45VEN_EPON_CTRL_REG_EOC_MODE_POLARITY_SHIFT (5U)
#define BRPHY_CL45VEN_EPON_CTRL_REG_EOC_MODE_POL_CORR_MASK (0x10U)
#define BRPHY_CL45VEN_EPON_CTRL_REG_EOC_MODE_POL_CORR_SHIFT (4U)
#define BRPHY_CL45VEN_EPON_CTRL_REG_EOC_SPEED_DET_THLD_MASK (0xfU)
#define BRPHY_CL45VEN_EPON_CTRL_REG_EOC_SPEED_DET_THLD_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_EEE_TEST_CTRL_A_TYPE;
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_MSG_10XNP_RX_EN_MASK (0x800U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_MSG_10XNP_RX_EN_SHIFT (11U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_MSG_10XNP_TX_EN_MASK (0x400U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_MSG_10XNP_TX_EN_SHIFT (10U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_MSG_10_RX_EN_MASK (0x200U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_MSG_10_RX_EN_SHIFT (9U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_MSG_10_TX_EN_MASK (0x100U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_MSG_10_TX_EN_SHIFT (8U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_LPI_GPCS_TEST_BUS_EN_MASK (0x80U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_LPI_GPCS_TEST_BUS_EN_SHIFT (7U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_MACSEC_PK_MODE_MASK (0x40U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_MACSEC_PK_MODE_SHIFT (6U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_MSG_11_VS_10_MASK (0x20U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_MSG_11_VS_10_SHIFT (5U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_MSG_9_EEE_MASK (0x10U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_MSG_9_EEE_SHIFT (4U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_MSG_9_EEE_SHIFTED_MASK (0x8U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_MSG_9_EEE_SHIFTED_SHIFT (3U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_OVERRIDE_LP_M10_MASK (0x2U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_OVERRIDE_LP_M10_SHIFT (1U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_OVERRIDE_LD_M10_MASK (0x1U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_A_OVERRIDE_LD_M10_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_EEE_TEST_CTRL_B_TYPE;
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_LPI_FEATURE_EN_MASK (0x8000U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_LPI_FEATURE_EN_SHIFT (15U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_LPI_FEATURE_EN_DIG1000X_MASK (0x4000U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_LPI_FEATURE_EN_DIG1000X_SHIFT (14U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_ETMFLQ_MASK (0x2000U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_ETMFLQ_SHIFT (13U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_EN_TEST_MODE_FOR_REG_3_20_MASK (0x1000U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_EN_TEST_MODE_FOR_REG_3_20_SHIFT (12U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_EN_10BASE_TE_RES_MASK (0x800U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_EN_10BASE_TE_RES_SHIFT (11U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_EN_10BASE_TE_10BASE_T_RES_MASK (0x400U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_EN_10BASE_TE_10BASE_T_RES_SHIFT (10U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_DET_SEND_Z_MASK (0x200U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_DET_SEND_Z_SHIFT (9U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_EN_DET_SEND_Z_OVERRIDE_MASK (0x100U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_EN_DET_SEND_Z_OVERRIDE_SHIFT (8U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_REM_UPD_DONE_TEST_MASK (0x80U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_REM_UPD_DONE_TEST_SHIFT (7U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_REM_LPI_REQ_TEST_MASK (0x40U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_REM_LPI_REQ_TEST_SHIFT (6U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_LOC_UPD_DONE_TEST_MASK (0x20U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_LOC_UPD_DONE_TEST_SHIFT (5U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_LOC_LPI_REQ_TEST_MASK (0x10U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_LOC_LPI_REQ_TEST_SHIFT (4U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_EN_REM_UPD_DONE_OVERRIDE_MASK (0x8U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_EN_REM_UPD_DONE_OVERRIDE_SHIFT (3U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_EN_REM_LPI_REQ_OVERRIDE_MASK (0x4U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_EN_REM_LPI_REQ_OVERRIDE_SHIFT (2U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_EN_LOC_UPD_DONE_OVERRIDE_MASK (0x2U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_EN_LOC_UPD_DONE_OVERRIDE_SHIFT (1U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_EN_LOC_LPI_REQ_OVERRIDE_MASK (0x1U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_B_EN_LOC_LPI_REQ_OVERRIDE_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_EEE_TEST_CTRL_C_TYPE;
#define BRPHY_CL45VEN_EEE_TEST_CTRL_C_MSG_6_XNP_RX_EN_MASK (0x8000U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_C_MSG_6_XNP_RX_EN_SHIFT (15U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_C_MSG_6_XNP_TX_EN_MASK (0x4000U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_C_MSG_6_XNP_TX_EN_SHIFT (14U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_C_MSG_6_RX_EN_MASK (0x2000U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_C_MSG_6_RX_EN_SHIFT (13U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_C_MSG_6_TX_EN_MASK (0x1000U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_C_MSG_6_TX_EN_SHIFT (12U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_C_MSG_5_XNP_RX_EN_MASK (0x800U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_C_MSG_5_XNP_RX_EN_SHIFT (11U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_C_MSG_5_XNP_TX_EN_MASK (0x400U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_C_MSG_5_XNP_TX_EN_SHIFT (10U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_C_MSG_5_RX_EN_MASK (0x200U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_C_MSG_5_RX_EN_SHIFT (9U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_C_MSG_5_TX_EN_MASK (0x100U)
#define BRPHY_CL45VEN_EEE_TEST_CTRL_C_MSG_5_TX_EN_SHIFT (8U)




typedef uint16_t BRPHY_CL45VEN_EEE_SPARE_1_TYPE;
#define BRPHY_CL45VEN_EEE_SPARE_1_SPARE_MASK (0xffffU)
#define BRPHY_CL45VEN_EEE_SPARE_1_SPARE_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_EEE_SPARE_2_TYPE;
#define BRPHY_CL45VEN_EEE_SPARE_2_SPARE_MASK (0xffffU)
#define BRPHY_CL45VEN_EEE_SPARE_2_SPARE_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_EEE_CONTROL_TYPE;
#define BRPHY_CL45VEN_EEE_CONTROL_LPI_FEATURE_EN_MASK (0x8000U)
#define BRPHY_CL45VEN_EEE_CONTROL_LPI_FEATURE_EN_SHIFT (15U)
#define BRPHY_CL45VEN_EEE_CONTROL_LPI_FEATURE_EN_DIG1000X_MASK (0x4000U)
#define BRPHY_CL45VEN_EEE_CONTROL_LPI_FEATURE_EN_DIG1000X_SHIFT (14U)
#define BRPHY_CL45VEN_EEE_CONTROL_LPI_RES_IN_FORCE_MODE_EN_MASK (0x2000U)
#define BRPHY_CL45VEN_EEE_CONTROL_LPI_RES_IN_FORCE_MODE_EN_SHIFT (13U)
#define BRPHY_CL45VEN_EEE_CONTROL_SPARE_MASK (0x1ff8U)
#define BRPHY_CL45VEN_EEE_CONTROL_SPARE_SHIFT (3U)
#define BRPHY_CL45VEN_EEE_CONTROL_LPI_LINKUP_DISABLE_MASK (0x4U)
#define BRPHY_CL45VEN_EEE_CONTROL_LPI_LINKUP_DISABLE_SHIFT (2U)
#define BRPHY_CL45VEN_EEE_CONTROL_EEE_DOWNGRADE_ENABLE_MASK (0x2U)
#define BRPHY_CL45VEN_EEE_CONTROL_EEE_DOWNGRADE_ENABLE_SHIFT (1U)
#define BRPHY_CL45VEN_EEE_CONTROL_LPI_100TX_BRCM_LINK_MASK (0x1U)
#define BRPHY_CL45VEN_EEE_CONTROL_LPI_100TX_BRCM_LINK_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_EEE_RES_STAT_TYPE;
#define BRPHY_CL45VEN_EEE_RES_STAT_MASK_1000T_EEE_MASK (0x40U)
#define BRPHY_CL45VEN_EEE_RES_STAT_MASK_1000T_EEE_SHIFT (6U)
#define BRPHY_CL45VEN_EEE_RES_STAT_MASK_100TX_EEE_MASK (0x20U)
#define BRPHY_CL45VEN_EEE_RES_STAT_MASK_100TX_EEE_SHIFT (5U)
#define BRPHY_CL45VEN_EEE_RES_STAT_MASK_10T_EEE_MASK (0x10U)
#define BRPHY_CL45VEN_EEE_RES_STAT_MASK_10T_EEE_SHIFT (4U)
#define BRPHY_CL45VEN_EEE_RES_STAT_1000T_RES_MASK (0x4U)
#define BRPHY_CL45VEN_EEE_RES_STAT_1000T_RES_SHIFT (2U)
#define BRPHY_CL45VEN_EEE_RES_STAT_100TX_RES_MASK (0x2U)
#define BRPHY_CL45VEN_EEE_RES_STAT_100TX_RES_SHIFT (1U)
#define BRPHY_CL45VEN_EEE_RES_STAT_10BASE_TE_RES_MASK (0x1U)
#define BRPHY_CL45VEN_EEE_RES_STAT_10BASE_TE_RES_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LPI_MODE_CNTR_TYPE;
#define BRPHY_CL45VEN_LPI_MODE_CNTR_COUNTER_MASK (0xffffU)
#define BRPHY_CL45VEN_LPI_MODE_CNTR_COUNTER_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LOC_DEV_MSG_5_A_TYPE;
#define BRPHY_CL45VEN_LOC_DEV_MSG_5_A_BITS_10_0_OF_5_MASK (0x7ffU)
#define BRPHY_CL45VEN_LOC_DEV_MSG_5_A_BITS_10_0_OF_5_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LOC_DEV_MSG_5_B_TYPE;
#define BRPHY_CL45VEN_LOC_DEV_MSG_5_B_BITS_21_11_OF_5_MASK (0x7ffU)
#define BRPHY_CL45VEN_LOC_DEV_MSG_5_B_BITS_21_11_OF_5_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LOC_DEV_MSG_5_C_TYPE;
#define BRPHY_CL45VEN_LOC_DEV_MSG_5_C_BITS_32_22_OF_5_MASK (0x7ffU)
#define BRPHY_CL45VEN_LOC_DEV_MSG_5_C_BITS_32_22_OF_5_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LOC_DEV_MSG_5_D_TYPE;
#define BRPHY_CL45VEN_LOC_DEV_MSG_5_D_BITS_43_33_OF_5_MASK (0x7ffU)
#define BRPHY_CL45VEN_LOC_DEV_MSG_5_D_BITS_43_33_OF_5_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LPM5A_TYPE;
#define BRPHY_CL45VEN_LPM5A_BITS_10_0_OF_LNK_PARTNR_MSG_5_MASK (0x7ffU)
#define BRPHY_CL45VEN_LPM5A_BITS_10_0_OF_LNK_PARTNR_MSG_5_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LPM5B_TYPE;
#define BRPHY_CL45VEN_LPM5B_BITS_21_11_OF_LNK_PARTNR_MSG_5_MASK (0x7ffU)
#define BRPHY_CL45VEN_LPM5B_BITS_21_11_OF_LNK_PARTNR_MSG_5_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LPM5C_TYPE;
#define BRPHY_CL45VEN_LPM5C_BITS_32_22_OF_LNK_PARTNR_MSG_5_MASK (0x7ffU)
#define BRPHY_CL45VEN_LPM5C_BITS_32_22_OF_LNK_PARTNR_MSG_5_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LPM5D_TYPE;
#define BRPHY_CL45VEN_LPM5D_MSG_5_OUI_MATCH_MASK (0x8000U)
#define BRPHY_CL45VEN_LPM5D_MSG_5_OUI_MATCH_SHIFT (15U)
#define BRPHY_CL45VEN_LPM5D_BITS_43_33_OF_LNK_PARTNR_MSG_5_MASK (0x7ffU)
#define BRPHY_CL45VEN_LPM5D_BITS_43_33_OF_LNK_PARTNR_MSG_5_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LOC_DEV_MSG_6_A_TYPE;
#define BRPHY_CL45VEN_LOC_DEV_MSG_6_A_BITS_10_0_OF_6_MASK (0x7ffU)
#define BRPHY_CL45VEN_LOC_DEV_MSG_6_A_BITS_10_0_OF_6_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LOC_DEV_MSG_6_B_TYPE;
#define BRPHY_CL45VEN_LOC_DEV_MSG_6_B_BITS_21_17_OF_6_MASK (0x7c0U)
#define BRPHY_CL45VEN_LOC_DEV_MSG_6_B_BITS_21_17_OF_6_SHIFT (6U)
#define BRPHY_CL45VEN_LOC_DEV_MSG_6_B_BITS_111_OF_6_MASK (0x3fU)
#define BRPHY_CL45VEN_LOC_DEV_MSG_6_B_BITS_111_OF_6_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LOC_DEV_MSG_6_C_TYPE;
#define BRPHY_CL45VEN_LOC_DEV_MSG_6_C_BITS_32_23_OF_6_MASK (0x7feU)
#define BRPHY_CL45VEN_LOC_DEV_MSG_6_C_BITS_32_23_OF_6_SHIFT (1U)
#define BRPHY_CL45VEN_LOC_DEV_MSG_6_C_BITS_22_22_OF_6_MASK (0x1U)
#define BRPHY_CL45VEN_LOC_DEV_MSG_6_C_BITS_22_22_OF_6_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LOC_DEV_MSG_6_D_TYPE;
#define BRPHY_CL45VEN_LOC_DEV_MSG_6_D_BITS_43_33_OF_6_MASK (0x7ffU)
#define BRPHY_CL45VEN_LOC_DEV_MSG_6_D_BITS_43_33_OF_6_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LPM6A_TYPE;
#define BRPHY_CL45VEN_LPM6A_BITS_10_0_OF_LNK_PARTNR_MSG_6_MASK (0x7ffU)
#define BRPHY_CL45VEN_LPM6A_BITS_10_0_OF_LNK_PARTNR_MSG_6_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LPM6B_TYPE;
#define BRPHY_CL45VEN_LPM6B_BITS_21_11_OF_LNK_PARTNR_MSG_6_MASK (0x7ffU)
#define BRPHY_CL45VEN_LPM6B_BITS_21_11_OF_LNK_PARTNR_MSG_6_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LPM6C_TYPE;
#define BRPHY_CL45VEN_LPM6C_BITS_32_22_OF_LNK_PARTNR_MSG_6_MASK (0x7ffU)
#define BRPHY_CL45VEN_LPM6C_BITS_32_22_OF_LNK_PARTNR_MSG_6_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_LPM6D_TYPE;
#define BRPHY_CL45VEN_LPM6D_MSG_6_OUI_MATCH_MASK (0x8000U)
#define BRPHY_CL45VEN_LPM6D_MSG_6_OUI_MATCH_SHIFT (15U)
#define BRPHY_CL45VEN_LPM6D_MSG_6_MODEL_MATCH_MASK (0x4000U)
#define BRPHY_CL45VEN_LPM6D_MSG_6_MODEL_MATCH_SHIFT (14U)
#define BRPHY_CL45VEN_LPM6D_MSG_6_REV_MATCH_MASK (0x2000U)
#define BRPHY_CL45VEN_LPM6D_MSG_6_REV_MATCH_SHIFT (13U)
#define BRPHY_CL45VEN_LPM6D_BITS_43_33_OF_LNK_PARTNR_MSG_6_MASK (0x7ffU)
#define BRPHY_CL45VEN_LPM6D_BITS_43_33_OF_LNK_PARTNR_MSG_6_SHIFT (0U)




typedef volatile struct COMP_PACKED _BRPHY_CL45VEN_RDBType {
    BRPHY_CL45VEN_FORCE_LINK_TYPE force_link; /* OFFSET: 0x0 */
    BRPHY_CL45VEN_SELECTIVE_RESET_TYPE selective_reset; /* OFFSET: 0x2 */
    BRPHY_CL45VEN_TEST_FSM_EXT_NXT_PGS_TYPE test_fsm_ext_nxt_pgs; /* OFFSET: 0x4 */
    BRPHY_CL45VEN_TEST_FSM_NXT_PGS_TYPE test_fsm_nxt_pgs; /* OFFSET: 0x6 */
    BRPHY_CL45VEN_RESERVED_TYPE rsvd0[42]; /* OFFSET: 0x8 */
    BRPHY_CL45VEN_AN_MAN_TEST_TYPE an_man_test; /* OFFSET: 0x32 */
    BRPHY_CL45VEN_AMLPAA_TYPE an_man_lnk_partnr_abi_a; /* OFFSET: 0x34 */
    BRPHY_CL45VEN_AMLPAB_TYPE an_man_lnk_partnr_abi_b; /* OFFSET: 0x36 */
    BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_A_TYPE lnk_partnr_nxt_pg_a; /* OFFSET: 0x38 */
    BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_B_TYPE lnk_partnr_nxt_pg_b; /* OFFSET: 0x3a */
    BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_C_TYPE lnk_partnr_nxt_pg_c; /* OFFSET: 0x3c */
    BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_D_TYPE lnk_partnr_nxt_pg_d; /* OFFSET: 0x3e */
    BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_E_TYPE lnk_partnr_nxt_pg_e; /* OFFSET: 0x40 */
    BRPHY_CL45VEN_LNK_PARTNR_NXT_PG_F_TYPE lnk_partnr_nxt_pg_f; /* OFFSET: 0x42 */
    BRPHY_CL45VEN_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x44 */
    BRPHY_CL45VEN_EPON_CTRL_REG_TYPE epon_ctrl_reg; /* OFFSET: 0x46 */
    BRPHY_CL45VEN_RESERVED_TYPE rsvd2[24]; /* OFFSET: 0x48 */
    BRPHY_CL45VEN_EEE_TEST_CTRL_A_TYPE eee_test_ctrl_a; /* OFFSET: 0x60 */
    BRPHY_CL45VEN_EEE_TEST_CTRL_B_TYPE eee_test_ctrl_b; /* OFFSET: 0x62 */
    BRPHY_CL45VEN_EEE_TEST_CTRL_C_TYPE eee_test_ctrl_c; /* OFFSET: 0x64 */
    BRPHY_CL45VEN_RESERVED_TYPE rsvd3[16]; /* OFFSET: 0x66 */
    BRPHY_CL45VEN_EEE_SPARE_1_TYPE eee_spare_1; /* OFFSET: 0x76 */
    BRPHY_CL45VEN_EEE_SPARE_2_TYPE eee_spare_2; /* OFFSET: 0x78 */
    BRPHY_CL45VEN_EEE_CONTROL_TYPE eee_control; /* OFFSET: 0x7a */
    BRPHY_CL45VEN_EEE_RES_STAT_TYPE eee_res_stat; /* OFFSET: 0x7c */
    BRPHY_CL45VEN_LPI_MODE_CNTR_TYPE lpi_mode_cntr; /* OFFSET: 0x7e */
    BRPHY_CL45VEN_LOC_DEV_MSG_5_A_TYPE loc_dev_msg_5_a; /* OFFSET: 0x80 */
    BRPHY_CL45VEN_LOC_DEV_MSG_5_B_TYPE loc_dev_msg_5_b; /* OFFSET: 0x82 */
    BRPHY_CL45VEN_LOC_DEV_MSG_5_C_TYPE loc_dev_msg_5_c; /* OFFSET: 0x84 */
    BRPHY_CL45VEN_LOC_DEV_MSG_5_D_TYPE loc_dev_msg_5_d; /* OFFSET: 0x86 */
    BRPHY_CL45VEN_LPM5A_TYPE lnk_partnr_msg_5_a; /* OFFSET: 0x88 */
    BRPHY_CL45VEN_LPM5B_TYPE lnk_partnr_msg_5_b; /* OFFSET: 0x8a */
    BRPHY_CL45VEN_LPM5C_TYPE lnk_partnr_msg_5_c; /* OFFSET: 0x8c */
    BRPHY_CL45VEN_LPM5D_TYPE lnk_partnr_msg_5_d; /* OFFSET: 0x8e */
    BRPHY_CL45VEN_LOC_DEV_MSG_6_A_TYPE loc_dev_msg_6_a; /* OFFSET: 0x90 */
    BRPHY_CL45VEN_LOC_DEV_MSG_6_B_TYPE loc_dev_msg_6_b; /* OFFSET: 0x92 */
    BRPHY_CL45VEN_LOC_DEV_MSG_6_C_TYPE loc_dev_msg_6_c; /* OFFSET: 0x94 */
    BRPHY_CL45VEN_LOC_DEV_MSG_6_D_TYPE loc_dev_msg_6_d; /* OFFSET: 0x96 */
    BRPHY_CL45VEN_LPM6A_TYPE lnk_partnr_msg_6_a; /* OFFSET: 0x98 */
    BRPHY_CL45VEN_LPM6B_TYPE lnk_partnr_msg_6_b; /* OFFSET: 0x9a */
    BRPHY_CL45VEN_LPM6C_TYPE lnk_partnr_msg_6_c; /* OFFSET: 0x9c */
    BRPHY_CL45VEN_LPM6D_TYPE lnk_partnr_msg_6_d; /* OFFSET: 0x9e */
} BRPHY_CL45VEN_RDBType;


#define BRPHY1_CL45VEN_BASE             (0x490F0000UL)

#define BRPHY2_CL45VEN_BASE             (0x494F0000UL)

#define BRPHY3_CL45VEN_BASE             (0x498F0000UL)

#define BRPHY4_CL45VEN_BASE             (0x49CF0000UL)



#define BRPHY_CL45VEN_MAX_HW_ID         (4UL)


#define BRPHY0_CL45VEN_CTRL_BASE        (BRPHY1_CL45VEN_BASE)


#define BRPHY1_CL45VEN_CTRL_BASE        (BRPHY2_CL45VEN_BASE)


#define BRPHY2_CL45VEN_CTRL_BASE        (BRPHY3_CL45VEN_BASE)


#define BRPHY3_CL45VEN_CTRL_BASE        (BRPHY4_CL45VEN_BASE)


#define BRPHY4_CL45VEN_CTRL_BASE        (UNDEFINED)


#define BRPHY_CL45VEN_0x102REG_MANUAL_FORCE_MASK  (0x8000U)


#define BRPHY_CL45VEN_0x102REG_MASTER_MASK  (0x4000U)


#define BRPHY_CL45VEN_0x102REG_100MBPS_MASK  (0x0800U)

#endif /* BRPHY_CL45VEN_RDB_H */
