/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file ieee_cl22_rdb.h
    @brief RDB File for IEEE_CL22

    @version 2019Jan21_rdb
*/

#ifndef IEEE_CL22_RDB_H
#define IEEE_CL22_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t IEEE_CL22_MIICNTL_TYPE;
#define IEEE_CL22_MIICNTL_RST_HW_MASK (0x8000U)
#define IEEE_CL22_MIICNTL_RST_HW_SHIFT (15U)
#define IEEE_CL22_MIICNTL_GLOOPBACK_MASK (0x4000U)
#define IEEE_CL22_MIICNTL_GLOOPBACK_SHIFT (14U)
#define IEEE_CL22_MIICNTL_MANUAL_SPEED0_MASK (0x2000U)
#define IEEE_CL22_MIICNTL_MANUAL_SPEED0_SHIFT (13U)
#define IEEE_CL22_MIICNTL_AUTONEG_ENABLE_MASK (0x1000U)
#define IEEE_CL22_MIICNTL_AUTONEG_ENABLE_SHIFT (12U)
#define IEEE_CL22_MIICNTL_PWRDWN_SW_MASK (0x800U)
#define IEEE_CL22_MIICNTL_PWRDWN_SW_SHIFT (11U)
#define IEEE_CL22_MIICNTL_RESTART_AUTONEG_MASK (0x200U)
#define IEEE_CL22_MIICNTL_RESTART_AUTONEG_SHIFT (9U)
#define IEEE_CL22_MIICNTL_DUPLEX_MASK (0x100U)
#define IEEE_CL22_MIICNTL_DUPLEX_SHIFT (8U)
#define IEEE_CL22_MIICNTL_COLLISION_TEST_EN_MASK (0x80U)
#define IEEE_CL22_MIICNTL_COLLISION_TEST_EN_SHIFT (7U)
#define IEEE_CL22_MIICNTL_MANUAL_SPEED1_MASK (0x40U)
#define IEEE_CL22_MIICNTL_MANUAL_SPEED1_SHIFT (6U)




typedef uint16_t IEEE_CL22_MIISTAT_TYPE;
#define IEEE_CL22_MIISTAT_S100BASE_T4_CAPABLE_MASK (0x8000U)
#define IEEE_CL22_MIISTAT_S100BASE_T4_CAPABLE_SHIFT (15U)
#define IEEE_CL22_MIISTAT_S100BASE_X_FULL_DUPLEX_CAPABLE_MASK (0x4000U)
#define IEEE_CL22_MIISTAT_S100BASE_X_FULL_DUPLEX_CAPABLE_SHIFT (14U)
#define IEEE_CL22_MIISTAT_S100BASE_X_HALF_DUPLEX_CAPABLE_MASK (0x2000U)
#define IEEE_CL22_MIISTAT_S100BASE_X_HALF_DUPLEX_CAPABLE_SHIFT (13U)
#define IEEE_CL22_MIISTAT_S10BASE_T_FULL_DUPLEX_CAPABLE_MASK (0x1000U)
#define IEEE_CL22_MIISTAT_S10BASE_T_FULL_DUPLEX_CAPABLE_SHIFT (12U)
#define IEEE_CL22_MIISTAT_S10BASE_T_HALF_DUPLEX_CAPABLE_MASK (0x800U)
#define IEEE_CL22_MIISTAT_S10BASE_T_HALF_DUPLEX_CAPABLE_SHIFT (11U)
#define IEEE_CL22_MIISTAT_S100BASE_T2_FULL_DUPLEX_CAPABLE_MASK (0x400U)
#define IEEE_CL22_MIISTAT_S100BASE_T2_FULL_DUPLEX_CAPABLE_SHIFT (10U)
#define IEEE_CL22_MIISTAT_S100BASE_T2_HALF_DUPLEX_CAPABLE_MASK (0x200U)
#define IEEE_CL22_MIISTAT_S100BASE_T2_HALF_DUPLEX_CAPABLE_SHIFT (9U)
#define IEEE_CL22_MIISTAT_EXTENDED_STATUS_MASK (0x100U)
#define IEEE_CL22_MIISTAT_EXTENDED_STATUS_SHIFT (8U)
#define IEEE_CL22_MIISTAT_MF_PREAMBLE_SUPRESSION_MASK (0x40U)
#define IEEE_CL22_MIISTAT_MF_PREAMBLE_SUPRESSION_SHIFT (6U)
#define IEEE_CL22_MIISTAT_AUTONEG_COMPLETE_MASK (0x20U)
#define IEEE_CL22_MIISTAT_AUTONEG_COMPLETE_SHIFT (5U)
#define IEEE_CL22_MIISTAT_REMOTE_FAULT_STAT_MASK (0x10U)
#define IEEE_CL22_MIISTAT_REMOTE_FAULT_STAT_SHIFT (4U)
#define IEEE_CL22_MIISTAT_AUTONEG_ABILITY_MASK (0x8U)
#define IEEE_CL22_MIISTAT_AUTONEG_ABILITY_SHIFT (3U)
#define IEEE_CL22_MIISTAT_LINK_STATUS_MASK (0x4U)
#define IEEE_CL22_MIISTAT_LINK_STATUS_SHIFT (2U)
#define IEEE_CL22_MIISTAT_JABBER_DETECT_MASK (0x2U)
#define IEEE_CL22_MIISTAT_JABBER_DETECT_SHIFT (1U)
#define IEEE_CL22_MIISTAT_EXTENDED_CAPABILITY_MASK (0x1U)
#define IEEE_CL22_MIISTAT_EXTENDED_CAPABILITY_SHIFT (0U)




typedef uint16_t IEEE_CL22_ID1_TYPE;
#define IEEE_CL22_ID1_REGID_MASK (0xffffU)
#define IEEE_CL22_ID1_REGID_SHIFT (0U)




typedef uint16_t IEEE_CL22_ID2_TYPE;
#define IEEE_CL22_ID2_REGID_MASK (0xffffU)
#define IEEE_CL22_ID2_REGID_SHIFT (0U)




typedef uint16_t IEEE_CL22_AUTONEGADV_TYPE;
#define IEEE_CL22_AUTONEGADV_NEXT_PAGE_MASK (0x8000U)
#define IEEE_CL22_AUTONEGADV_NEXT_PAGE_SHIFT (15U)
#define IEEE_CL22_AUTONEGADV_REMOTE_FAULT_MASK (0x3000U)
#define IEEE_CL22_AUTONEGADV_REMOTE_FAULT_SHIFT (12U)
#define IEEE_CL22_AUTONEGADV_PAUSE_MASK (0x180U)
#define IEEE_CL22_AUTONEGADV_PAUSE_SHIFT (7U)
#define IEEE_CL22_AUTONEGADV_HALF_DUPLEX_MASK (0x40U)
#define IEEE_CL22_AUTONEGADV_HALF_DUPLEX_SHIFT (6U)
#define IEEE_CL22_AUTONEGADV_FULL_DUPLEX_MASK (0x20U)
#define IEEE_CL22_AUTONEGADV_FULL_DUPLEX_SHIFT (5U)




typedef uint16_t IEEE_CL22_AUTONEGLPABIL_TYPE;
#define IEEE_CL22_AUTONEGLPABIL_MR_LP_ADV_ABILITY_MASK (0xffffU)
#define IEEE_CL22_AUTONEGLPABIL_MR_LP_ADV_ABILITY_SHIFT (0U)




typedef uint16_t IEEE_CL22_AUTONEGEXP_TYPE;
#define IEEE_CL22_AUTONEGEXP_NEXT_PAGE_ABILITY_MASK (0x4U)
#define IEEE_CL22_AUTONEGEXP_NEXT_PAGE_ABILITY_SHIFT (2U)
#define IEEE_CL22_AUTONEGEXP_LATCH_PAGE_RX_MASK (0x2U)
#define IEEE_CL22_AUTONEGEXP_LATCH_PAGE_RX_SHIFT (1U)




typedef uint16_t IEEE_CL22_AUTONEGNP_TYPE;
#define IEEE_CL22_AUTONEGNP_NEXT_PAGE_MASK (0x8000U)
#define IEEE_CL22_AUTONEGNP_NEXT_PAGE_SHIFT (15U)
#define IEEE_CL22_AUTONEGNP_ACK_MASK (0x4000U)
#define IEEE_CL22_AUTONEGNP_ACK_SHIFT (14U)
#define IEEE_CL22_AUTONEGNP_MESSAGE_PAGE_MASK (0x2000U)
#define IEEE_CL22_AUTONEGNP_MESSAGE_PAGE_SHIFT (13U)
#define IEEE_CL22_AUTONEGNP_ACK2_MASK (0x1000U)
#define IEEE_CL22_AUTONEGNP_ACK2_SHIFT (12U)
#define IEEE_CL22_AUTONEGNP_TOGGLE_MASK (0x800U)
#define IEEE_CL22_AUTONEGNP_TOGGLE_SHIFT (11U)
#define IEEE_CL22_AUTONEGNP_MESSAGE_MASK (0x7ffU)
#define IEEE_CL22_AUTONEGNP_MESSAGE_SHIFT (0U)




typedef uint16_t IEEE_CL22_AUTONEGLPNP_TYPE;
#define IEEE_CL22_AUTONEGLPNP_MR_LP_NP_RX_O_MASK (0xffffU)
#define IEEE_CL22_AUTONEGLPNP_MR_LP_NP_RX_O_SHIFT (0U)




typedef uint8_t IEEE_CL22_RESERVED_TYPE;




typedef uint16_t IEEE_CL22_MMD_ACCESSCONTROL_TYPE;
#define IEEE_CL22_MMD_ACCESSCONTROL_INCREMENT_CTRL_MASK (0xc000U)
#define IEEE_CL22_MMD_ACCESSCONTROL_INCREMENT_CTRL_SHIFT (14U)
#define IEEE_CL22_MMD_ACCESSCONTROL_DEVAD_MASK (0x1fU)
#define IEEE_CL22_MMD_ACCESSCONTROL_DEVAD_SHIFT (0U)




typedef uint16_t IEEE_CL22_MMD_ACCESSADDRDATA_TYPE;
#define IEEE_CL22_MMD_ACCESSADDRDATA_ADDRDATA_MASK (0xffffU)
#define IEEE_CL22_MMD_ACCESSADDRDATA_ADDRDATA_SHIFT (0U)




typedef uint16_t IEEE_CL22_MIIEXTSTAT_TYPE;
#define IEEE_CL22_MIIEXTSTAT_S1000BASE_X_FULL_DUPLEX_CAPABLE_MASK (0x8000U)
#define IEEE_CL22_MIIEXTSTAT_S1000BASE_X_FULL_DUPLEX_CAPABLE_SHIFT (15U)
#define IEEE_CL22_MIIEXTSTAT_S1000BASE_X_HALF_DUPLEX_CAPABLE_MASK (0x4000U)
#define IEEE_CL22_MIIEXTSTAT_S1000BASE_X_HALF_DUPLEX_CAPABLE_SHIFT (14U)
#define IEEE_CL22_MIIEXTSTAT_S1000BASE_T_FULL_DUPLEX_CAPABLE_MASK (0x2000U)
#define IEEE_CL22_MIIEXTSTAT_S1000BASE_T_FULL_DUPLEX_CAPABLE_SHIFT (13U)
#define IEEE_CL22_MIIEXTSTAT_S1000BASE_T_HALF_DUPLEX_CAPABLE_MASK (0x1000U)
#define IEEE_CL22_MIIEXTSTAT_S1000BASE_T_HALF_DUPLEX_CAPABLE_SHIFT (12U)




typedef volatile struct COMP_PACKED _IEEE_CL22_RDBType {
    IEEE_CL22_MIICNTL_TYPE miicntl; /* OFFSET: 0x0 */
    IEEE_CL22_MIISTAT_TYPE miistat; /* OFFSET: 0x2 */
    IEEE_CL22_ID1_TYPE id1; /* OFFSET: 0x4 */
    IEEE_CL22_ID2_TYPE id2; /* OFFSET: 0x6 */
    IEEE_CL22_AUTONEGADV_TYPE autonegadv; /* OFFSET: 0x8 */
    IEEE_CL22_AUTONEGLPABIL_TYPE autoneglpabil; /* OFFSET: 0xa */
    IEEE_CL22_AUTONEGEXP_TYPE autonegexp; /* OFFSET: 0xc */
    IEEE_CL22_AUTONEGNP_TYPE autonegnp; /* OFFSET: 0xe */
    IEEE_CL22_AUTONEGLPNP_TYPE autoneglpabil2; /* OFFSET: 0x10 */
    IEEE_CL22_RESERVED_TYPE rsvd0[8]; /* OFFSET: 0x12 */
    IEEE_CL22_MMD_ACCESSCONTROL_TYPE mmd_accesscontrol; /* OFFSET: 0x1a */
    IEEE_CL22_MMD_ACCESSADDRDATA_TYPE mmd_accessad; /* OFFSET: 0x1c */
    IEEE_CL22_MIIEXTSTAT_TYPE miiextstat; /* OFFSET: 0x1e */
} IEEE_CL22_RDBType;


#define SG0_CL22_B0_BASE                (0x4A400000UL)

#define SG1_CL22_B0_BASE                (0x4A420000UL)

#define SG2_CL22_B0_BASE                (0x4A440000UL)

#define SG3_CL22_B0_BASE                (0x4A460000UL)

#define SGP_CL22_B0_BASE                (0x4A480000UL)



#define IEEE_CL22_MAX_HW_ID             (5UL)

#endif /* IEEE_CL22_RDB_H */
