/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file io_rdb.h
    @brief RDB File for IO

    @version 2019Jan21_rdb
*/

#ifndef IO_RDB_H
#define IO_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t IO_MII1_CONFIG_TYPE;
#define IO_MII1_CONFIG_CLOCK_EN_MII1_MASK (0x8000U)
#define IO_MII1_CONFIG_CLOCK_EN_MII1_SHIFT (15U)
#define IO_MII1_CONFIG_SRC_MII1_MASK (0x60U)
#define IO_MII1_CONFIG_SRC_MII1_SHIFT (5U)
#define IO_MII1_CONFIG_AMP_ENABLE_MII1_MASK (0x10U)
#define IO_MII1_CONFIG_AMP_ENABLE_MII1_SHIFT (4U)
#define IO_MII1_CONFIG_SEL_MII1_MASK (0xeU)
#define IO_MII1_CONFIG_SEL_MII1_SHIFT (1U)
#define IO_MII1_CONFIG_SPARE_MASK (0x1U)
#define IO_MII1_CONFIG_SPARE_SHIFT (0U)




typedef uint16_t IO_MII2_CONFIG_TYPE;
#define IO_MII2_CONFIG_CLOCK_EN_MII2_MASK (0x8000U)
#define IO_MII2_CONFIG_CLOCK_EN_MII2_SHIFT (15U)
#define IO_MII2_CONFIG_SRC_MII2_MASK (0x60U)
#define IO_MII2_CONFIG_SRC_MII2_SHIFT (5U)
#define IO_MII2_CONFIG_AMP_ENABLE_MII2_MASK (0x10U)
#define IO_MII2_CONFIG_AMP_ENABLE_MII2_SHIFT (4U)
#define IO_MII2_CONFIG_SEL_MII2_MASK (0xeU)
#define IO_MII2_CONFIG_SEL_MII2_SHIFT (1U)
#define IO_MII2_CONFIG_SPARE_MASK (0x1U)
#define IO_MII2_CONFIG_SPARE_SHIFT (0U)




typedef uint16_t IO_HYSTERESIS_TYPE;
#define IO_HYSTERESIS_HYS_MASK (0xffU)
#define IO_HYSTERESIS_HYS_SHIFT (0U)




typedef uint16_t IO_SOURCE_TYPE;
#define IO_SOURCE_SRC_MASK (0xffU)
#define IO_SOURCE_SRC_SHIFT (0U)




typedef uint16_t IO_SEL_TYPE;
#define IO_SEL_FLASH_MASK (0x7000U)
#define IO_SEL_FLASH_SHIFT (12U)
#define IO_SEL_MISC_MASK (0xe00U)
#define IO_SEL_MISC_SHIFT (9U)
#define IO_SEL_I2C_MASK (0x1c0U)
#define IO_SEL_I2C_SHIFT (6U)
#define IO_SEL_GPIO_MASK (0x38U)
#define IO_SEL_GPIO_SHIFT (3U)
#define IO_SEL_SPI_SLV_MASK (0x7U)
#define IO_SEL_SPI_SLV_SHIFT (0U)




typedef uint16_t IO_MII1_MODEHV_TYPE;
#define IO_MII1_MODEHV_MODEHV_MASK (0x1U)
#define IO_MII1_MODEHV_MODEHV_SHIFT (0U)




typedef uint16_t IO_MII2_MODEHV_TYPE;
#define IO_MII2_MODEHV_MII1_MODEHV_MASK (0x1U)
#define IO_MII2_MODEHV_MII1_MODEHV_SHIFT (0U)




typedef uint8_t IO_RESERVED_TYPE;




typedef uint16_t IO_RGMII1_CTL_TYPE;
#define IO_RGMII1_CTL_DIS_IMP_MASK (0x8000U)
#define IO_RGMII1_CTL_DIS_IMP_SHIFT (15U)
#define IO_RGMII1_CTL_RMII_CLOCK_DIRECTION_MASK (0x8U)
#define IO_RGMII1_CTL_RMII_CLOCK_DIRECTION_SHIFT (3U)
#define IO_RGMII1_CTL_RGMII1_CTL_MASK (0x6U)
#define IO_RGMII1_CTL_RGMII1_CTL_SHIFT (1U)
#define IO_RGMII1_CTL_RGMII1_BYPASS_IMP_2NS_DEL_MASK (0x1U)
#define IO_RGMII1_CTL_RGMII1_BYPASS_IMP_2NS_DEL_SHIFT (0U)




typedef uint16_t IO_RGMII2_CTL_TYPE;
#define IO_RGMII2_CTL_DIS_IMP_MASK (0x8000U)
#define IO_RGMII2_CTL_DIS_IMP_SHIFT (15U)
#define IO_RGMII2_CTL_RMII_CLOCK_DIRECTION_MASK (0x8U)
#define IO_RGMII2_CTL_RMII_CLOCK_DIRECTION_SHIFT (3U)
#define IO_RGMII2_CTL_RGMII2_CTL_MASK (0x6U)
#define IO_RGMII2_CTL_RGMII2_CTL_SHIFT (1U)
#define IO_RGMII2_CTL_RGMII2_BYPASS_IMP_2NS_DEL_MASK (0x1U)
#define IO_RGMII2_CTL_RGMII2_BYPASS_IMP_2NS_DEL_SHIFT (0U)




typedef uint16_t IO_SGMII_RGMII_CTL_TYPE;
#define IO_SGMII_RGMII_CTL_SEL_P8_P6_PCIE_MASK (0x8U)
#define IO_SGMII_RGMII_CTL_SEL_P8_P6_PCIE_SHIFT (3U)
#define IO_SGMII_RGMII_CTL_SEL_P1_MASK (0x4U)
#define IO_SGMII_RGMII_CTL_SEL_P1_SHIFT (2U)
#define IO_SGMII_RGMII_CTL_SEL_RGMII1_MASK (0x2U)
#define IO_SGMII_RGMII_CTL_SEL_RGMII1_SHIFT (1U)
#define IO_SGMII_RGMII_CTL_SEL_RGMII2_MASK (0x1U)
#define IO_SGMII_RGMII_CTL_SEL_RGMII2_SHIFT (0U)




typedef uint16_t IO_RGMII1_GMII_CTL_TYPE;
#define IO_RGMII1_GMII_CTL_RGMII_RX_PAUSE_MASK (0x10U)
#define IO_RGMII1_GMII_CTL_RGMII_RX_PAUSE_SHIFT (4U)
#define IO_RGMII1_GMII_CTL_RGMII_TX_PAUSE_MASK (0x8U)
#define IO_RGMII1_GMII_CTL_RGMII_TX_PAUSE_SHIFT (3U)
#define IO_RGMII1_GMII_CTL_RGMII_LINK_MASK (0x4U)
#define IO_RGMII1_GMII_CTL_RGMII_LINK_SHIFT (2U)
#define IO_RGMII1_GMII_CTL_RGMII_SPD_MASK (0x3U)
#define IO_RGMII1_GMII_CTL_RGMII_SPD_SHIFT (0U)




typedef uint16_t IO_RGMII2_GMII_CTL_TYPE;
#define IO_RGMII2_GMII_CTL_RGMII_RX_PAUSE_MASK (0x10U)
#define IO_RGMII2_GMII_CTL_RGMII_RX_PAUSE_SHIFT (4U)
#define IO_RGMII2_GMII_CTL_RGMII_TX_PAUSE_MASK (0x8U)
#define IO_RGMII2_GMII_CTL_RGMII_TX_PAUSE_SHIFT (3U)
#define IO_RGMII2_GMII_CTL_RGMII_LINK_MASK (0x4U)
#define IO_RGMII2_GMII_CTL_RGMII_LINK_SHIFT (2U)
#define IO_RGMII2_GMII_CTL_RGMII_SPD_MASK (0x3U)
#define IO_RGMII2_GMII_CTL_RGMII_SPD_SHIFT (0U)




typedef uint16_t IO_CPU_GMII_CTL_TYPE;
#define IO_CPU_GMII_CTL_LPBK_SEL_MASK (0x100U)
#define IO_CPU_GMII_CTL_LPBK_SEL_SHIFT (8U)
#define IO_CPU_GMII_CTL_RX_PAUSE_MASK (0x10U)
#define IO_CPU_GMII_CTL_RX_PAUSE_SHIFT (4U)
#define IO_CPU_GMII_CTL_TX_PAUSE_MASK (0x8U)
#define IO_CPU_GMII_CTL_TX_PAUSE_SHIFT (3U)
#define IO_CPU_GMII_CTL_LINK_MASK (0x4U)
#define IO_CPU_GMII_CTL_LINK_SHIFT (2U)
#define IO_CPU_GMII_CTL_SPD_MASK (0x3U)
#define IO_CPU_GMII_CTL_SPD_SHIFT (0U)




typedef uint16_t IO_STRAPS_RAW_TYPE;
#define IO_STRAPS_RAW_SFT_DEBUG_MODE_MASK (0x8000U)
#define IO_STRAPS_RAW_SFT_DEBUG_MODE_SHIFT (15U)
#define IO_STRAPS_RAW_TC10_GO2STNDBY_MASK (0x4000U)
#define IO_STRAPS_RAW_TC10_GO2STNDBY_SHIFT (14U)
#define IO_STRAPS_RAW_TC10_DISABLE_MASK (0x2000U)
#define IO_STRAPS_RAW_TC10_DISABLE_SHIFT (13U)
#define IO_STRAPS_RAW_PHYADDR4_MASK (0x1000U)
#define IO_STRAPS_RAW_PHYADDR4_SHIFT (12U)
#define IO_STRAPS_RAW_PHYADDR3_MASK (0x800U)
#define IO_STRAPS_RAW_PHYADDR3_SHIFT (11U)
#define IO_STRAPS_RAW_MII2_MODE_2_MASK (0x400U)
#define IO_STRAPS_RAW_MII2_MODE_2_SHIFT (10U)
#define IO_STRAPS_RAW_MII1_MODE_2_MASK (0x200U)
#define IO_STRAPS_RAW_MII1_MODE_2_SHIFT (9U)
#define IO_STRAPS_RAW_HW_FWDG_EN_MASK (0x100U)
#define IO_STRAPS_RAW_HW_FWDG_EN_SHIFT (8U)
#define IO_STRAPS_RAW_MII2_MODE_1_MASK (0x80U)
#define IO_STRAPS_RAW_MII2_MODE_1_SHIFT (7U)
#define IO_STRAPS_RAW_MII2_MODE_0_MASK (0x40U)
#define IO_STRAPS_RAW_MII2_MODE_0_SHIFT (6U)
#define IO_STRAPS_RAW_MII1_MODE_1_MASK (0x20U)
#define IO_STRAPS_RAW_MII1_MODE_1_SHIFT (5U)
#define IO_STRAPS_RAW_MII1_MODE_0_MASK (0x10U)
#define IO_STRAPS_RAW_MII1_MODE_0_SHIFT (4U)
#define IO_STRAPS_RAW_JTCE_STRAP_MASK (0x8U)
#define IO_STRAPS_RAW_JTCE_STRAP_SHIFT (3U)
#define IO_STRAPS_RAW_SFT_FORCE_DWNLD_MASK (0x4U)
#define IO_STRAPS_RAW_SFT_FORCE_DWNLD_SHIFT (2U)
#define IO_STRAPS_RAW_BRPHY_MS_STRAP_MASK (0x2U)
#define IO_STRAPS_RAW_BRPHY_MS_STRAP_SHIFT (1U)
#define IO_STRAPS_RAW_STRAP_ENEXTCK_MASK (0x1U)
#define IO_STRAPS_RAW_STRAP_ENEXTCK_SHIFT (0U)




typedef uint16_t IO_STRAPS_OV_TYPE;
#define IO_STRAPS_OV_SFT_DEBUG_MODE_MASK (0x8000U)
#define IO_STRAPS_OV_SFT_DEBUG_MODE_SHIFT (15U)
#define IO_STRAPS_OV_TC10_GO2STNDBY_MASK (0x4000U)
#define IO_STRAPS_OV_TC10_GO2STNDBY_SHIFT (14U)
#define IO_STRAPS_OV_TC10_DISABLE_MASK (0x2000U)
#define IO_STRAPS_OV_TC10_DISABLE_SHIFT (13U)
#define IO_STRAPS_OV_MII2_MODE_2_MASK (0x400U)
#define IO_STRAPS_OV_MII2_MODE_2_SHIFT (10U)
#define IO_STRAPS_OV_MII1_MODE_2_MASK (0x200U)
#define IO_STRAPS_OV_MII1_MODE_2_SHIFT (9U)
#define IO_STRAPS_OV_HW_FWDG_EN_MASK (0x100U)
#define IO_STRAPS_OV_HW_FWDG_EN_SHIFT (8U)
#define IO_STRAPS_OV_MII2_MODE_1_MASK (0x80U)
#define IO_STRAPS_OV_MII2_MODE_1_SHIFT (7U)
#define IO_STRAPS_OV_MII2_MODE_0_MASK (0x40U)
#define IO_STRAPS_OV_MII2_MODE_0_SHIFT (6U)
#define IO_STRAPS_OV_MII1_MODE_1_MASK (0x20U)
#define IO_STRAPS_OV_MII1_MODE_1_SHIFT (5U)
#define IO_STRAPS_OV_MII1_MODE_0_MASK (0x10U)
#define IO_STRAPS_OV_MII1_MODE_0_SHIFT (4U)
#define IO_STRAPS_OV_JTCE_STRAP_MASK (0x8U)
#define IO_STRAPS_OV_JTCE_STRAP_SHIFT (3U)
#define IO_STRAPS_OV_SFT_FORCE_DWNLD_MASK (0x4U)
#define IO_STRAPS_OV_SFT_FORCE_DWNLD_SHIFT (2U)
#define IO_STRAPS_OV_BRPHY_MS_STRAP_MASK (0x2U)
#define IO_STRAPS_OV_BRPHY_MS_STRAP_SHIFT (1U)
#define IO_STRAPS_OV_STRAP_ENEXTCK_MASK (0x1U)
#define IO_STRAPS_OV_STRAP_ENEXTCK_SHIFT (0U)




typedef uint16_t IO_SW_OVRD_TYPE;
#define IO_SW_OVRD_RX_PAUSE_SEL_MASK (0x800U)
#define IO_SW_OVRD_RX_PAUSE_SEL_SHIFT (11U)
#define IO_SW_OVRD_TX_PAUSE_SEL_MASK (0x400U)
#define IO_SW_OVRD_TX_PAUSE_SEL_SHIFT (10U)
#define IO_SW_OVRD_LINK_SEL_MASK (0x200U)
#define IO_SW_OVRD_LINK_SEL_SHIFT (9U)
#define IO_SW_OVRD_SPD_SEL_MASK (0x100U)
#define IO_SW_OVRD_SPD_SEL_SHIFT (8U)
#define IO_SW_OVRD_RX_PAUSE_VAL_MASK (0x10U)
#define IO_SW_OVRD_RX_PAUSE_VAL_SHIFT (4U)
#define IO_SW_OVRD_TX_PAUSE_VAL_MASK (0x8U)
#define IO_SW_OVRD_TX_PAUSE_VAL_SHIFT (3U)
#define IO_SW_OVRD_LINK_VAL_MASK (0x4U)
#define IO_SW_OVRD_LINK_VAL_SHIFT (2U)
#define IO_SW_OVRD_SPD_VAL_MASK (0x3U)
#define IO_SW_OVRD_SPD_VAL_SHIFT (0U)




typedef uint16_t IO_TEST_BUS_SELECT_TYPE;
#define IO_TEST_BUS_SELECT_OVSTB_MASK (0x8000U)
#define IO_TEST_BUS_SELECT_OVSTB_SHIFT (15U)
#define IO_TEST_BUS_SELECT_BURNIN_EN_MASK (0x4000U)
#define IO_TEST_BUS_SELECT_BURNIN_EN_SHIFT (14U)
#define IO_TEST_BUS_SELECT_SELECT_TEST_BUS_MASK (0xfU)
#define IO_TEST_BUS_SELECT_SELECT_TEST_BUS_SHIFT (0U)




typedef uint16_t IO_P1588_CONFIG_TYPE;
#define IO_P1588_CONFIG_SYNC_OUT_SEL_MASK (0x1U)
#define IO_P1588_CONFIG_SYNC_OUT_SEL_SHIFT (0U)




typedef uint16_t IO_P1588_SYNC_GEN_TYPE;
#define IO_P1588_SYNC_GEN_IN1_8P_MASK (0x8U)
#define IO_P1588_SYNC_GEN_IN1_8P_SHIFT (3U)
#define IO_P1588_SYNC_GEN_IN0_8P_MASK (0x4U)
#define IO_P1588_SYNC_GEN_IN0_8P_SHIFT (2U)
#define IO_P1588_SYNC_GEN_IN1_1P_MASK (0x2U)
#define IO_P1588_SYNC_GEN_IN1_1P_SHIFT (1U)
#define IO_P1588_SYNC_GEN_IN0_1P_MASK (0x1U)
#define IO_P1588_SYNC_GEN_IN0_1P_SHIFT (0U)




typedef uint16_t IO_CTL_TYPE;
#define IO_CTL_QSPI_MODE_STRAP_MASK (0x10U)
#define IO_CTL_QSPI_MODE_STRAP_SHIFT (4U)
#define IO_CTL_MDIOM_DISABLE_MASK (0x2U)
#define IO_CTL_MDIOM_DISABLE_SHIFT (1U)
#define IO_CTL_SPIM_DISABLE_MASK (0x1U)
#define IO_CTL_SPIM_DISABLE_SHIFT (0U)




typedef uint16_t IO_RGMII_FIFO_CTL_TYPE;
#define IO_RGMII_FIFO_CTL_SFT_RESET_MASK (0x8000U)
#define IO_RGMII_FIFO_CTL_SFT_RESET_SHIFT (15U)
#define IO_RGMII_FIFO_CTL_ELASTICITYMODE_MASK (0x3000U)
#define IO_RGMII_FIFO_CTL_ELASTICITYMODE_SHIFT (12U)
#define IO_RGMII_FIFO_CTL_SAFETY_DISABLE_MASK (0x800U)
#define IO_RGMII_FIFO_CTL_SAFETY_DISABLE_SHIFT (11U)
#define IO_RGMII_FIFO_CTL_FIFO_ENABLE_MASK (0x400U)
#define IO_RGMII_FIFO_CTL_FIFO_ENABLE_SHIFT (10U)
#define IO_RGMII_FIFO_CTL_LPI_FEATURE_EN_MASK (0x200U)
#define IO_RGMII_FIFO_CTL_LPI_FEATURE_EN_SHIFT (9U)
#define IO_RGMII_FIFO_CTL_WRBLOCK_MODE_MASK (0x100U)
#define IO_RGMII_FIFO_CTL_WRBLOCK_MODE_SHIFT (8U)
#define IO_RGMII_FIFO_CTL_WRBLOCK_OVR_MASK (0xf0U)
#define IO_RGMII_FIFO_CTL_WRBLOCK_OVR_SHIFT (4U)
#define IO_RGMII_FIFO_CTL_MIN_IPG_MASK (0xfU)
#define IO_RGMII_FIFO_CTL_MIN_IPG_SHIFT (0U)




typedef uint16_t IO_RGMII_DLL_CTL_TYPE;
#define IO_RGMII_DLL_CTL_IDDQ_MASK (0x10U)
#define IO_RGMII_DLL_CTL_IDDQ_SHIFT (4U)
#define IO_RGMII_DLL_CTL_CLK_PH_MASK (0xfU)
#define IO_RGMII_DLL_CTL_CLK_PH_SHIFT (0U)




typedef uint16_t IO_FF_TYPE;
#define IO_FF_IOFF_MASK (0xffffU)
#define IO_FF_IOFF_SHIFT (0U)




typedef volatile struct COMP_PACKED _IO_RDBType {
    IO_MII1_CONFIG_TYPE mii1_config; /* OFFSET: 0x0 */
    IO_MII2_CONFIG_TYPE mii2_config; /* OFFSET: 0x2 */
    IO_HYSTERESIS_TYPE io_hysteresis; /* OFFSET: 0x4 */
    IO_SOURCE_TYPE io_source; /* OFFSET: 0x6 */
    IO_SEL_TYPE io_sel; /* OFFSET: 0x8 */
    IO_MII1_MODEHV_TYPE io_mii1_modehv; /* OFFSET: 0xa */
    IO_MII2_MODEHV_TYPE io_mii2_modehv; /* OFFSET: 0xc */
    IO_RESERVED_TYPE rsvd0[18]; /* OFFSET: 0xe */
    IO_RGMII1_CTL_TYPE rgmii1_ctl; /* OFFSET: 0x20 */
    IO_RGMII2_CTL_TYPE rgmii2_ctl; /* OFFSET: 0x22 */
    IO_SGMII_RGMII_CTL_TYPE sgmii_rgmii_ctl; /* OFFSET: 0x24 */
    IO_RGMII1_GMII_CTL_TYPE rgmii1_gmii_ctl; /* OFFSET: 0x26 */
    IO_RGMII2_GMII_CTL_TYPE rgmii2_gmii_ctl; /* OFFSET: 0x28 */
    IO_CPU_GMII_CTL_TYPE cpu_gmii_ctl; /* OFFSET: 0x2a */
    IO_RESERVED_TYPE rsvd1[20]; /* OFFSET: 0x2c */
    IO_STRAPS_RAW_TYPE straps_raw; /* OFFSET: 0x40 */
    IO_STRAPS_OV_TYPE straps_ov; /* OFFSET: 0x42 */
    IO_RESERVED_TYPE rsvd2[12]; /* OFFSET: 0x44 */
    IO_SW_OVRD_TYPE sw_ovrd[9]; /* OFFSET: 0x50 */
    IO_RESERVED_TYPE rsvd3[14]; /* OFFSET: 0x62 */
    IO_TEST_BUS_SELECT_TYPE test_bus_select; /* OFFSET: 0x70 */
    IO_P1588_CONFIG_TYPE p1588_config; /* OFFSET: 0x72 */
    IO_P1588_SYNC_GEN_TYPE p1588_sync_gen; /* OFFSET: 0x74 */
    IO_CTL_TYPE io_ctl; /* OFFSET: 0x76 */
    IO_RGMII_FIFO_CTL_TYPE rgmii1_fifo_ctl; /* OFFSET: 0x78 */
    IO_RGMII_FIFO_CTL_TYPE rgmii2_fifo_ctl; /* OFFSET: 0x7a */
    IO_RGMII_DLL_CTL_TYPE rgmii1_dll_ctl; /* OFFSET: 0x7c */
    IO_RGMII_DLL_CTL_TYPE rgmii1_dll_cfg; /* OFFSET: 0x7e */
    IO_RGMII_DLL_CTL_TYPE rgmii2_dll_ctl; /* OFFSET: 0x80 */
    IO_RGMII_DLL_CTL_TYPE rgmii2_dll_cfg; /* OFFSET: 0x82 */
    IO_RESERVED_TYPE rsvd4[3962]; /* OFFSET: 0x84 */
    IO_FF_TYPE ioff; /* OFFSET: 0xffe */
} IO_RDBType;


#define IO_BASE                         (0x4A840000UL)



#define IO_MAX_HW_ID                    (1UL)


#define IO_NUM_RGMII_PORTS              (2U )

#endif /* IO_RDB_H */
