/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file otp_rdb.h
    @brief RDB File for OTP

    @version 2019Jan21_rdb
*/

#ifndef OTP_RDB_H
#define OTP_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t OTP_CPU_COMMAND_TYPE;
#define OTP_CPU_COMMAND_OPCODE_MASK (0x3fUL)
#define OTP_CPU_COMMAND_OPCODE_SHIFT (0UL)




typedef uint32_t OTP_CPU_WRDATA_TYPE;
#define OTP_CPU_WRDATA_WRDATA_MASK (0xffffffffUL)
#define OTP_CPU_WRDATA_WRDATA_SHIFT (0UL)




typedef uint32_t OTP_CONFIG_TYPE;
#define OTP_CONFIG_SOFT_RESET_MASK (0x4000UL)
#define OTP_CONFIG_SOFT_RESET_SHIFT (14UL)
#define OTP_CONFIG_SM_EN_PLL_RESET_MASK (0x400UL)
#define OTP_CONFIG_SM_EN_PLL_RESET_SHIFT (10UL)
#define OTP_CONFIG_OTP_DEV_MODE_ENABLE_MASK (0x200UL)
#define OTP_CONFIG_OTP_DEV_MODE_ENABLE_SHIFT (9UL)
#define OTP_CONFIG_OTP_PCIE_ENABLE_MASK (0x100UL)
#define OTP_CONFIG_OTP_PCIE_ENABLE_SHIFT (8UL)
#define OTP_CONFIG_OTP_CPU_JTAG_ENABLE_MASK (0x80UL)
#define OTP_CONFIG_OTP_CPU_JTAG_ENABLE_SHIFT (7UL)
#define OTP_CONFIG_OTP_OTP_JTAG_ENABLE_MASK (0x40UL)
#define OTP_CONFIG_OTP_OTP_JTAG_ENABLE_SHIFT (6UL)
#define OTP_CONFIG_OTP_MDIO_SLV_ENABLE_MASK (0x20UL)
#define OTP_CONFIG_OTP_MDIO_SLV_ENABLE_SHIFT (5UL)
#define OTP_CONFIG_OTP_SECURITY_MONITOR_ENABLE_MASK (0x10UL)
#define OTP_CONFIG_OTP_SECURITY_MONITOR_ENABLE_SHIFT (4UL)
#define OTP_CONFIG_OTP_SPI_SLV_ENABLE_MASK (0x8UL)
#define OTP_CONFIG_OTP_SPI_SLV_ENABLE_SHIFT (3UL)
#define OTP_CONFIG_OTP_CMD_WR_MASK (0x4UL)
#define OTP_CONFIG_OTP_CMD_WR_SHIFT (2UL)
#define OTP_CONFIG_OTP_CMD_MODE_MASK (0x2UL)
#define OTP_CONFIG_OTP_CMD_MODE_SHIFT (1UL)
#define OTP_CONFIG_DIS_OTP_ACC_MASK (0x1UL)
#define OTP_CONFIG_DIS_OTP_ACC_SHIFT (0UL)




typedef uint32_t OTP_ADDRESS_TYPE;
#define OTP_ADDRESS_ADDRESS_MASK (0x1ffUL)
#define OTP_ADDRESS_ADDRESS_SHIFT (0UL)




typedef uint32_t OTP_STATUS_TYPE;
#define OTP_STATUS_ECC_DED_FLAG_STATUS_MASK (0x800000UL)
#define OTP_STATUS_ECC_DED_FLAG_STATUS_SHIFT (23UL)
#define OTP_STATUS_ECC_SEC_FLAG_STATUS_MASK (0x400000UL)
#define OTP_STATUS_ECC_SEC_FLAG_STATUS_SHIFT (22UL)
#define OTP_STATUS_PRESCREEN_FAIL_MASK (0x100000UL)
#define OTP_STATUS_PRESCREEN_FAIL_SHIFT (20UL)
#define OTP_STATUS_ILLEGAL_ADDR_MASK (0x80000UL)
#define OTP_STATUS_ILLEGAL_ADDR_SHIFT (19UL)
#define OTP_STATUS_MAX_SW_MASK (0x40000UL)
#define OTP_STATUS_MAX_SW_SHIFT (18UL)
#define OTP_STATUS_AUTO_RW_MAX_MASK (0x20000UL)
#define OTP_STATUS_AUTO_RW_MAX_SHIFT (17UL)
#define OTP_STATUS_MAX_RWP_MASK (0x10000UL)
#define OTP_STATUS_MAX_RWP_SHIFT (16UL)
#define OTP_STATUS_MAX_RW_MASK (0x8000UL)
#define OTP_STATUS_MAX_RW_SHIFT (15UL)
#define OTP_STATUS_PG_WD_FP_FAIL_MASK (0x4000UL)
#define OTP_STATUS_PG_WD_FP_FAIL_SHIFT (14UL)
#define OTP_STATUS_PROG_EN_MASK (0x2000UL)
#define OTP_STATUS_PROG_EN_SHIFT (13UL)
#define OTP_STATUS_PROG_BLK_CMD_MASK (0x1000UL)
#define OTP_STATUS_PROG_BLK_CMD_SHIFT (12UL)
#define OTP_STATUS_PROG_SCR_FAIL_MASK (0x800UL)
#define OTP_STATUS_PROG_SCR_FAIL_SHIFT (11UL)
#define OTP_STATUS_PROG_WORD_FAIL_MASK (0x400UL)
#define OTP_STATUS_PROG_WORD_FAIL_SHIFT (10UL)
#define OTP_STATUS_INVALID_ADDR_MASK (0x200UL)
#define OTP_STATUS_INVALID_ADDR_SHIFT (9UL)
#define OTP_STATUS_DEBUG_MODE_MASK (0x100UL)
#define OTP_STATUS_DEBUG_MODE_SHIFT (8UL)
#define OTP_STATUS_MST_FSM_ERROR_MASK (0x80UL)
#define OTP_STATUS_MST_FSM_ERROR_SHIFT (7UL)
#define OTP_STATUS_DEBUG_MODE_SET_MASK (0x40UL)
#define OTP_STATUS_DEBUG_MODE_SET_SHIFT (6UL)
#define OTP_STATUS_REF_OK_MASK (0x20UL)
#define OTP_STATUS_REF_OK_SHIFT (5UL)
#define OTP_STATUS_CMD_FAIL_MASK (0x10UL)
#define OTP_STATUS_CMD_FAIL_SHIFT (4UL)
#define OTP_STATUS_FDONE_MASK (0x8UL)
#define OTP_STATUS_FDONE_SHIFT (3UL)
#define OTP_STATUS_PROG_OK_MASK (0x4UL)
#define OTP_STATUS_PROG_OK_SHIFT (2UL)
#define OTP_STATUS_CMD_DONE_MASK (0x2UL)
#define OTP_STATUS_CMD_DONE_SHIFT (1UL)
#define OTP_STATUS_DATA_VALID_MASK (0x1UL)
#define OTP_STATUS_DATA_VALID_SHIFT (0UL)




typedef uint32_t OTP_CPU_RDATA_TYPE;
#define OTP_CPU_RDATA_RDATA_MASK (0xffffffffUL)
#define OTP_CPU_RDATA_RDATA_SHIFT (0UL)




typedef uint32_t OTP_BISR_STATUS_TYPE;




typedef uint32_t OTP_ECC_INTERRUPT_TYPE;
#define OTP_ECC_INTERRUPT_ECC_DED_FLAG_INT_MASK (0x800000UL)
#define OTP_ECC_INTERRUPT_ECC_DED_FLAG_INT_SHIFT (23UL)
#define OTP_ECC_INTERRUPT_ECC_SEC_FLAG_INT_MASK (0x400000UL)
#define OTP_ECC_INTERRUPT_ECC_SEC_FLAG_INT_SHIFT (22UL)
#define OTP_ECC_INTERRUPT_UNUSED_INT_MASK (0x3fffffUL)
#define OTP_ECC_INTERRUPT_UNUSED_INT_SHIFT (0UL)




typedef uint32_t OTP_ECC_INTERRUPT_EN_REG_TYPE;
#define OTP_ECC_INTERRUPT_EN_REG_ECC_DED_FLAG_INT_EN_MASK (0x800000UL)
#define OTP_ECC_INTERRUPT_EN_REG_ECC_DED_FLAG_INT_EN_SHIFT (23UL)
#define OTP_ECC_INTERRUPT_EN_REG_ECC_SEC_FLAG_INT_EN_MASK (0x400000UL)
#define OTP_ECC_INTERRUPT_EN_REG_ECC_SEC_FLAG_INT_EN_SHIFT (22UL)
#define OTP_ECC_INTERRUPT_EN_REG_UNUSED_INT_EN_MASK (0x3fffffUL)
#define OTP_ECC_INTERRUPT_EN_REG_UNUSED_INT_EN_SHIFT (0UL)




typedef uint32_t OTP_ECC_INTERRUPT_CLR_REG_TYPE;
#define OTP_ECC_INTERRUPT_CLR_REG_ECC_DED_FLAG_INT_CLR_MASK (0x800000UL)
#define OTP_ECC_INTERRUPT_CLR_REG_ECC_DED_FLAG_INT_CLR_SHIFT (23UL)
#define OTP_ECC_INTERRUPT_CLR_REG_ECC_SEC_FLAG_INT_CLR_MASK (0x400000UL)
#define OTP_ECC_INTERRUPT_CLR_REG_ECC_SEC_FLAG_INT_CLR_SHIFT (22UL)
#define OTP_ECC_INTERRUPT_CLR_REG_UNUSED_INT_CLR_MASK (0x3fffffUL)
#define OTP_ECC_INTERRUPT_CLR_REG_UNUSED_INT_CLR_SHIFT (0UL)




typedef volatile struct COMP_PACKED _OTP_RDBType {
    OTP_CPU_COMMAND_TYPE cpu_command; /* OFFSET: 0x0 */
    OTP_CPU_WRDATA_TYPE cpu_wrdata; /* OFFSET: 0x4 */
    OTP_CONFIG_TYPE config; /* OFFSET: 0x8 */
    OTP_ADDRESS_TYPE address; /* OFFSET: 0xc */
    OTP_STATUS_TYPE status; /* OFFSET: 0x10 */
    OTP_CPU_RDATA_TYPE cpu_rdata; /* OFFSET: 0x14 */
    OTP_BISR_STATUS_TYPE bisr_status; /* OFFSET: 0x18 */
    OTP_ECC_INTERRUPT_TYPE ecc_interrupt; /* OFFSET: 0x1c */
    OTP_ECC_INTERRUPT_EN_REG_TYPE ecc_interrupt_en_reg; /* OFFSET: 0x20 */
    OTP_ECC_INTERRUPT_CLR_REG_TYPE ecc_interrupt_clr_reg; /* OFFSET: 0x24 */
} OTP_RDBType;


#define OTP_BASE                        (0x4C012000UL)



#define OTP_MAX_HW_ID                   (1UL)


#define OTP_ADDR_START                  (0UL)


#define OTP_ADDR_END                    (255UL)


#define OTP_DATA_MASK_WITH_ECC          (0xFFFFFFFUL)


#define OTP_ECC_BITS                    (6UL)


#define OTP_ADDR_BRCM_REG_START         (12UL)


#define OTP_ADDR_BRCM_REG_END           (63UL)

#endif /* OTP_RDB_H */
