/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file xgxsblk0_rdb.h
    @brief RDB File for XGXSBLK0

    @version 2019Jan21_rdb
*/

#ifndef XGXSBLK0_RDB_H
#define XGXSBLK0_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t XGXSBLK0_XGXSCONTROL_TYPE;
#define XGXSBLK0_XGXSCONTROL_START_SEQUENCER_MASK (0x2000U)
#define XGXSBLK0_XGXSCONTROL_START_SEQUENCER_SHIFT (13U)
#define XGXSBLK0_XGXSCONTROL_RESET_ANLG_MASK (0x1000U)
#define XGXSBLK0_XGXSCONTROL_RESET_ANLG_SHIFT (12U)
#define XGXSBLK0_XGXSCONTROL_MODE_MASK (0xf00U)
#define XGXSBLK0_XGXSCONTROL_MODE_SHIFT (8U)
#define XGXSBLK0_XGXSCONTROL_PLL_BYPASS_MASK (0x80U)
#define XGXSBLK0_XGXSCONTROL_PLL_BYPASS_SHIFT (7U)
#define XGXSBLK0_XGXSCONTROL_RLOOP_MASK (0x40U)
#define XGXSBLK0_XGXSCONTROL_RLOOP_SHIFT (6U)
#define XGXSBLK0_XGXSCONTROL_HSTL_MASK (0x20U)
#define XGXSBLK0_XGXSCONTROL_HSTL_SHIFT (5U)
#define XGXSBLK0_XGXSCONTROL_MDIO_CONT_EN_MASK (0x10U)
#define XGXSBLK0_XGXSCONTROL_MDIO_CONT_EN_SHIFT (4U)
#define XGXSBLK0_XGXSCONTROL_CDET_EN_MASK (0x8U)
#define XGXSBLK0_XGXSCONTROL_CDET_EN_SHIFT (3U)
#define XGXSBLK0_XGXSCONTROL_EDEN_MASK (0x4U)
#define XGXSBLK0_XGXSCONTROL_EDEN_SHIFT (2U)
#define XGXSBLK0_XGXSCONTROL_AFRST_EN_MASK (0x2U)
#define XGXSBLK0_XGXSCONTROL_AFRST_EN_SHIFT (1U)
#define XGXSBLK0_XGXSCONTROL_TXCKO_DIV_MASK (0x1U)
#define XGXSBLK0_XGXSCONTROL_TXCKO_DIV_SHIFT (0U)




typedef uint16_t XGXSBLK0_XGXSSTATUS_TYPE;
#define XGXSBLK0_XGXSSTATUS_STATUS_EN_MASK (0x8000U)
#define XGXSBLK0_XGXSSTATUS_STATUS_EN_SHIFT (15U)
#define XGXSBLK0_XGXSSTATUS_TX_REMOTE_FAULT_MASK (0x2000U)
#define XGXSBLK0_XGXSSTATUS_TX_REMOTE_FAULT_SHIFT (13U)
#define XGXSBLK0_XGXSSTATUS_RX_REMOTE_FAULT_MASK (0x1000U)
#define XGXSBLK0_XGXSSTATUS_RX_REMOTE_FAULT_SHIFT (12U)
#define XGXSBLK0_XGXSSTATUS_TXPLL_LOCK_MASK (0x800U)
#define XGXSBLK0_XGXSSTATUS_TXPLL_LOCK_SHIFT (11U)
#define XGXSBLK0_XGXSSTATUS_TXD_FIFO_ERR_MASK (0x400U)
#define XGXSBLK0_XGXSSTATUS_TXD_FIFO_ERR_SHIFT (10U)
#define XGXSBLK0_XGXSSTATUS_SEQUENCER_DONE_MASK (0x200U)
#define XGXSBLK0_XGXSSTATUS_SEQUENCER_DONE_SHIFT (9U)
#define XGXSBLK0_XGXSSTATUS_SEQUENCER_PASS_MASK (0x100U)
#define XGXSBLK0_XGXSSTATUS_SEQUENCER_PASS_SHIFT (8U)
#define XGXSBLK0_XGXSSTATUS_RXFERR_MASK (0xf0U)
#define XGXSBLK0_XGXSSTATUS_RXFERR_SHIFT (4U)
#define XGXSBLK0_XGXSSTATUS_CKCMP_UNFLOW_MASK (0x4U)
#define XGXSBLK0_XGXSSTATUS_CKCMP_UNFLOW_SHIFT (2U)
#define XGXSBLK0_XGXSSTATUS_CKCMP_OVFLOW_MASK (0x2U)
#define XGXSBLK0_XGXSSTATUS_CKCMP_OVFLOW_SHIFT (1U)
#define XGXSBLK0_XGXSSTATUS_SKEW_STATUS_MASK (0x1U)
#define XGXSBLK0_XGXSSTATUS_SKEW_STATUS_SHIFT (0U)




typedef uint8_t XGXSBLK0_RESERVED_TYPE;




typedef uint16_t XGXSBLK0_MMDSELECT_TYPE;
#define XGXSBLK0_MMDSELECT_MULTIPRTS_EN_MASK (0x8000U)
#define XGXSBLK0_MMDSELECT_MULTIPRTS_EN_SHIFT (15U)
#define XGXSBLK0_MMDSELECT_MULTIMMDS_EN_MASK (0x4000U)
#define XGXSBLK0_MMDSELECT_MULTIMMDS_EN_SHIFT (14U)
#define XGXSBLK0_MMDSELECT_PRTAD_BCST_DISABLE_MASK (0x2000U)
#define XGXSBLK0_MMDSELECT_PRTAD_BCST_DISABLE_SHIFT (13U)
#define XGXSBLK0_MMDSELECT_DEVAN_EN_MASK (0x8U)
#define XGXSBLK0_MMDSELECT_DEVAN_EN_SHIFT (3U)
#define XGXSBLK0_MMDSELECT_DEVPMD_EN_MASK (0x4U)
#define XGXSBLK0_MMDSELECT_DEVPMD_EN_SHIFT (2U)
#define XGXSBLK0_MMDSELECT_DEVDEVAD_EN_MASK (0x2U)
#define XGXSBLK0_MMDSELECT_DEVDEVAD_EN_SHIFT (1U)
#define XGXSBLK0_MMDSELECT_DEVCL22_EN_MASK (0x1U)
#define XGXSBLK0_MMDSELECT_DEVCL22_EN_SHIFT (0U)




typedef uint16_t XGXSBLK0_MISCCONTROL1_TYPE;
#define XGXSBLK0_MISCCONTROL1_GLOBAL_PMD_TX_DISABLE_MASK (0x800U)
#define XGXSBLK0_MISCCONTROL1_GLOBAL_PMD_TX_DISABLE_SHIFT (11U)
#define XGXSBLK0_MISCCONTROL1_PCS_DEV_EN_OVERRIDE_MASK (0x400U)
#define XGXSBLK0_MISCCONTROL1_PCS_DEV_EN_OVERRIDE_SHIFT (10U)
#define XGXSBLK0_MISCCONTROL1_PMD_DEV_EN_OVERRIDE_MASK (0x200U)
#define XGXSBLK0_MISCCONTROL1_PMD_DEV_EN_OVERRIDE_SHIFT (9U)
#define XGXSBLK0_MISCCONTROL1_AN_DEV_EN_TMP_MASK (0x100U)
#define XGXSBLK0_MISCCONTROL1_AN_DEV_EN_TMP_SHIFT (8U)
#define XGXSBLK0_MISCCONTROL1_CLEAR_LINKDOWN_MASK (0x80U)
#define XGXSBLK0_MISCCONTROL1_CLEAR_LINKDOWN_SHIFT (7U)
#define XGXSBLK0_MISCCONTROL1_LATCH_LINKDOWN_ENABLE_MASK (0x40U)
#define XGXSBLK0_MISCCONTROL1_LATCH_LINKDOWN_ENABLE_SHIFT (6U)
#define XGXSBLK0_MISCCONTROL1_IEEE_BLKSEL_VAL1_MASK (0x20U)
#define XGXSBLK0_MISCCONTROL1_IEEE_BLKSEL_VAL1_SHIFT (5U)
#define XGXSBLK0_MISCCONTROL1_FORCE_DIV5_FOR_LXCK25_MASK (0x10U)
#define XGXSBLK0_MISCCONTROL1_FORCE_DIV5_FOR_LXCK25_SHIFT (4U)
#define XGXSBLK0_MISCCONTROL1_PARDET10G_PWRDNLINK_EN_MASK (0x8U)
#define XGXSBLK0_MISCCONTROL1_PARDET10G_PWRDNLINK_EN_SHIFT (3U)
#define XGXSBLK0_MISCCONTROL1_INVERT_RX_SIGDET_MASK (0x4U)
#define XGXSBLK0_MISCCONTROL1_INVERT_RX_SIGDET_SHIFT (2U)
#define XGXSBLK0_MISCCONTROL1_IEEE_BLKSEL_AUTODET_MASK (0x2U)
#define XGXSBLK0_MISCCONTROL1_IEEE_BLKSEL_AUTODET_SHIFT (1U)
#define XGXSBLK0_MISCCONTROL1_IEEE_BLKSEL_VAL_MASK (0x1U)
#define XGXSBLK0_MISCCONTROL1_IEEE_BLKSEL_VAL_SHIFT (0U)




typedef uint16_t XGXSBLK0_BLOCKADDRESS_TYPE;
#define XGXSBLK0_BLOCKADDRESS_BLOCKADDRESS_MASK (0x7ff0U)
#define XGXSBLK0_BLOCKADDRESS_BLOCKADDRESS_SHIFT (4U)




typedef volatile struct COMP_PACKED _XGXSBLK0_RDBType {
    XGXSBLK0_XGXSCONTROL_TYPE xgxscontrol; /* OFFSET: 0x0 */
    XGXSBLK0_XGXSSTATUS_TYPE xgxsstatus; /* OFFSET: 0x2 */
    XGXSBLK0_RESERVED_TYPE rsvd0[22]; /* OFFSET: 0x4 */
    XGXSBLK0_MMDSELECT_TYPE mmdselect; /* OFFSET: 0x1a */
    XGXSBLK0_MISCCONTROL1_TYPE misccontrol1; /* OFFSET: 0x1c */
    XGXSBLK0_BLOCKADDRESS_TYPE blockaddress; /* OFFSET: 0x1e */
} XGXSBLK0_RDBType;


#define BLK0_BASE                       (0x4A410000UL)



#define XGXSBLK0_MAX_HW_ID              (1UL)

#endif /* XGXSBLK0_RDB_H */
